language: node_js
node_js:
- '8'
- '7'
- '6'
- '5'
- '4'
- '0.12'
- '0.10'
matrix:
  allow_failures:
  - node_js: '8'
notifications:
  email:
    - watson@elastic.co
  slack:
    rooms:
      secure: PR+vjohDfGmidHhaIboj896iad3OIa4pked1Mib+XB5FF3tWfpDjBBNmEBizRbpwzxy4oHgOr22LBNvi+zkE674wXY3VUM+Wx9pJztlqotcON/hBjcJd993MfixRHN0RShxn4omaLfiqrZ+8iUFD5MQKdLKqBG/IG2toxdhuDkU=
    on_success: change
    on_failure: change
    on_pull_requests: false
